name = "ONNXKnet"
uuid = "0d2ecdea-6138-11e9-204d-f3cd490e15e2"
authors = ["ayush1999 <ayush.shridhar1999@gmail.com>"]
version = "0.1.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataFlow = "a237f610-4214-5ca7-a9c6-385896804134"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
